server.port=${SERVER_PORT}

spring.datasource.url=${SUPABASE_DB_HOST}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}

# Explicitly set PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Need to remove this and do this task manually in the database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Fix table creation order
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
